### ISSUE TITLE
RG41 or G41 dorm version sprite loaded not correctly

### ISSUE THREAD

**Issue by JustReadThis** [cullus/gfSpinePiXi#3]
Excuse me,
the animation of RG41 (or i should say G41 in dorm version) loaded not correctly.
G41 parts not properly arranged like the picture I attach.
I compared it with G43 animation.
Maybe you could fix this.

Thanks

![rg41](https://user-images.githubusercontent.com/33173203/41505322-884948ae-7230-11e8-92d6-f06d2cc01b93.jpg)

**Comment by cullus** [comment]
Thank you,this issue has been fixed.
